SUPPORTED_ENDPOINTS="""relocate/:host/:port/:belowHost/:belowPort
relocate-below/:host/:port/:belowHost/:belowPort
relocate-slaves/:host/:port/:belowHost/:belowPort
regroup-slaves/:host/:port
move-up/:host/:port
move-up-slaves/:host/:port
move-below/:host/:port/:siblingHost/:siblingPort
move-equivalent/:host/:port/:belowHost/:belowPort
repoint/:host/:port/:belowHost/:belowPort
repoint-slaves/:host/:port
make-co-master/:host/:port
enslave-siblings/:host/:port
enslave-master/:host/:port
master-equivalent/:host/:port/:logFile/:logPos
regroup-slaves-bls/:host/:port
move-below-gtid/:host/:port/:belowHost/:belowPort
move-slaves-gtid/:host/:port/:belowHost/:belowPort
regroup-slaves-gtid/:host/:port
match/:host/:port/:belowHost/:belowPort
match-below/:host/:port/:belowHost/:belowPort
match-up/:host/:port
match-slaves/:host/:port/:belowHost/:belowPort
match-up-slaves/:host/:port
regroup-slaves-pgtid/:host/:port
make-master/:host/:port
make-local-master/:host/:port
enable-gtid/:host/:port
disable-gtid/:host/:port
locate-gtid-errant/:host/:port
gtid-errant-reset-master/:host/:port
gtid-errant-inject-empty/:host/:port
skip-query/:host/:port
start-slave/:host/:port
restart-slave/:host/:port
stop-slave/:host/:port
stop-slave-nice/:host/:port
reset-slave/:host/:port
detach-slave/:host/:port
reattach-slave/:host/:port
detach-slave-master-host/:host/:port
reattach-slave-master-host/:host/:port
flush-binary-logs/:host/:port
purge-binary-logs/:host/:port/:logFile
restart-slave-statements/:host/:port
enable-semi-sync-master/:host/:port
disable-semi-sync-master/:host/:port
enable-semi-sync-replica/:host/:port
disable-semi-sync-replica/:host/:port
delay-replication/:host/:port/:seconds
can-replicate-from/:host/:port/:belowHost/:belowPort
can-replicate-from-gtid/:host/:port/:belowHost/:belowPort
set-read-only/:host/:port
set-writeable/:host/:port
kill-query/:host/:port/:process
last-pseudo-gtid/:host/:port
submit-pool-instances/:pool
cluster-pool-instances/:clusterName
cluster-pool-instances/:clusterName/:pool
heuristic-cluster-pool-instances/:clusterName
heuristic-cluster-pool-instances/:clusterName/:pool
heuristic-cluster-pool-lag/:clusterName
heuristic-cluster-pool-lag/:clusterName/:pool
search/:searchString
search
cluster/:clusterHint
cluster/alias/:clusterAlias
cluster/instance/:host/:port
cluster-info/:clusterHint
cluster-info/alias/:clusterAlias
cluster-osc-slaves/:clusterHint
set-cluster-alias/:clusterName
clusters
clusters-info
masters
master/:clusterHint
instance-replicas/:host/:port
all-instances
downtimed
downtimed/:clusterHint
topology/:clusterHint
topology/:host/:port
topology-tabulated/:clusterHint
topology-tabulated/:host/:port
topology-tags/:clusterHint
topology-tags/:host/:port
snapshot-topologies
submit-masters-to-kv-stores
submit-masters-to-kv-stores/:clusterHint
tagged
tags/:host/:port
tag-value/:host/:port
tag-value/:host/:port/:tagName
tag/:host/:port
tag/:host/:port/:tagName/:tagValue
untag/:host/:port
untag/:host/:port/:tagName
untag-all
untag-all/:tagName/:tagValue
instance/:host/:port
discover/:host/:port
async-discover/:host/:port
refresh/:host/:port
forget/:host/:port
forget-cluster/:clusterHint
begin-maintenance/:host/:port/:owner/:reason
end-maintenance/:host/:port
in-maintenance/:host/:port
end-maintenance/:maintenanceKey
maintenance
begin-downtime/:host/:port/:owner/:reason
begin-downtime/:host/:port/:owner/:reason/:duration
end-downtime/:host/:port
replication-analysis
replication-analysis/:clusterName
replication-analysis/instance/:host/:port
recover/:host/:port
recover/:host/:port/:candidateHost/:candidatePort
recover-lite/:host/:port
recover-lite/:host/:port/:candidateHost/:candidatePort
graceful-master-takeover/:host/:port
graceful-master-takeover/:host/:port/:designatedHost/:designatedPort
graceful-master-takeover/:clusterHint
graceful-master-takeover/:clusterHint/:designatedHost/:designatedPort
graceful-master-takeover-auto/:host/:port
graceful-master-takeover-auto/:host/:port/:designatedHost/:designatedPort
graceful-master-takeover-auto/:clusterHint
graceful-master-takeover-auto/:clusterHint/:designatedHost/:designatedPort
force-master-failover/:host/:port
force-master-failover/:clusterHint
force-master-takeover/:clusterHint/:designatedHost/:designatedPort
force-master-takeover/:host/:port/:designatedHost/:designatedPort
register-candidate/:host/:port/:promotionRule
automated-recovery-filters
audit-failure-detection
audit-failure-detection/:page
audit-failure-detection/id/:id
audit-failure-detection/alias/:clusterAlias
audit-failure-detection/alias/:clusterAlias/:page
replication-analysis-changelog
audit-recovery
audit-recovery/:page
audit-recovery/id/:id
audit-recovery/uid/:uid
audit-recovery/cluster/:clusterName
audit-recovery/cluster/:clusterName/:page
audit-recovery/alias/:clusterAlias
audit-recovery/alias/:clusterAlias/:page
audit-recovery-steps/:uid
active-cluster-recovery/:clusterName
recently-active-cluster-recovery/:clusterName
recently-active-instance-recovery/:host/:port
ack-recovery/cluster/:clusterHint
ack-recovery/cluster/alias/:clusterAlias
ack-recovery/instance/:host/:port
ack-recovery/:recoveryId
ack-recovery/uid/:uid
ack-all-recoveries
blocked-recoveries
blocked-recoveries/cluster/:clusterName
disable-global-recoveries
enable-global-recoveries
check-global-recoveries
problems
problems/:clusterName
audit
audit/:page
audit/instance/:host/:port
audit/instance/:host/:port/:page
resolve/:host/:port
raft-add-peer/:addr
raft-remove-peer/:addr
routed-leader-check
reelect
reload-cluster-alias
deregister-hostname-unresolve/:host/:port
register-hostname-unresolve/:host/:port/:virtualname
bulk-instances
bulk-promotion-rules
discovery-metrics-raw/:seconds
discovery-metrics-aggregated/:seconds
discovery-queue-metrics-raw/:seconds
discovery-queue-metrics-aggregated/:seconds
backend-query-metrics-raw/:seconds
backend-query-metrics-aggregated/:seconds
write-buffer-metrics-raw/:seconds
write-buffer-metrics-aggregated/:seconds
agents
agent/:host
agent-umount/:host
agent-mount/:host
agent-create-snapshot/:host
agent-removelv/:host
agent-mysql-stop/:host
agent-mysql-start/:host
agent-seed/:targetHost/:sourceHost
agent-active-seeds/:host
agent-recent-seeds/:host
agent-seed-details/:seedId
agent-seed-states/:seedId
agent-abort-seed/:seedId
agent-custom-command/:host/:command
seeds"""
